//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculationServiceReference
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CalculationServiceReference.ICalculationService")]
    public interface ICalculationService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculationService/AddTwoIntegers", ReplyAction="http://tempuri.org/ICalculationService/AddTwoIntegersResponse")]
        System.Threading.Tasks.Task<int> AddTwoIntegersAsync(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculationService/SubstractTwoIntegers", ReplyAction="http://tempuri.org/ICalculationService/SubstractTwoIntegersResponse")]
        System.Threading.Tasks.Task<int> SubstractTwoIntegersAsync(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculationService/MultiplyTwoIntegers", ReplyAction="http://tempuri.org/ICalculationService/MultiplyTwoIntegersResponse")]
        System.Threading.Tasks.Task<int> MultiplyTwoIntegersAsync(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculationService/DivideTwoIntegers", ReplyAction="http://tempuri.org/ICalculationService/DivideTwoIntegersResponse")]
        System.Threading.Tasks.Task<int> DivideTwoIntegersAsync(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculationService/SubstractTwoDoubles", ReplyAction="http://tempuri.org/ICalculationService/SubstractTwoDoublesResponse")]
        System.Threading.Tasks.Task<double> SubstractTwoDoublesAsync(double a, double b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculationService/AddTwoDoubles", ReplyAction="http://tempuri.org/ICalculationService/AddTwoDoublesResponse")]
        System.Threading.Tasks.Task<double> AddTwoDoublesAsync(double a, double b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculationService/MultiplyTwoDoubles", ReplyAction="http://tempuri.org/ICalculationService/MultiplyTwoDoublesResponse")]
        System.Threading.Tasks.Task<int> MultiplyTwoDoublesAsync(int a, int b);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculationService/DivideTwoDoubles", ReplyAction="http://tempuri.org/ICalculationService/DivideTwoDoublesResponse")]
        System.Threading.Tasks.Task<int> DivideTwoDoublesAsync(double a, double b);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public interface ICalculationServiceChannel : CalculationServiceReference.ICalculationService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public partial class CalculationServiceClient : System.ServiceModel.ClientBase<CalculationServiceReference.ICalculationService>, CalculationServiceReference.ICalculationService
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public CalculationServiceClient() : 
                base(CalculationServiceClient.GetDefaultBinding(), CalculationServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_ICalculationService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CalculationServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(CalculationServiceClient.GetBindingForEndpoint(endpointConfiguration), CalculationServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CalculationServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(CalculationServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CalculationServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(CalculationServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CalculationServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<int> AddTwoIntegersAsync(int a, int b)
        {
            return base.Channel.AddTwoIntegersAsync(a, b);
        }
        
        public System.Threading.Tasks.Task<int> SubstractTwoIntegersAsync(int a, int b)
        {
            return base.Channel.SubstractTwoIntegersAsync(a, b);
        }
        
        public System.Threading.Tasks.Task<int> MultiplyTwoIntegersAsync(int a, int b)
        {
            return base.Channel.MultiplyTwoIntegersAsync(a, b);
        }
        
        public System.Threading.Tasks.Task<int> DivideTwoIntegersAsync(int a, int b)
        {
            return base.Channel.DivideTwoIntegersAsync(a, b);
        }
        
        public System.Threading.Tasks.Task<double> SubstractTwoDoublesAsync(double a, double b)
        {
            return base.Channel.SubstractTwoDoublesAsync(a, b);
        }
        
        public System.Threading.Tasks.Task<double> AddTwoDoublesAsync(double a, double b)
        {
            return base.Channel.AddTwoDoublesAsync(a, b);
        }
        
        public System.Threading.Tasks.Task<int> MultiplyTwoDoublesAsync(int a, int b)
        {
            return base.Channel.MultiplyTwoDoublesAsync(a, b);
        }
        
        public System.Threading.Tasks.Task<int> DivideTwoDoublesAsync(double a, double b)
        {
            return base.Channel.DivideTwoDoublesAsync(a, b);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ICalculationService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ICalculationService))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:59127/CalculationService.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return CalculationServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_ICalculationService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return CalculationServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_ICalculationService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_ICalculationService,
        }
    }
}
